#!/usr/bin/env python3
import sys
import requests
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QLabel, QLineEdit, QPushButton, QDateEdit
import datetime

API_BASE_URL = "http://localhost:1234/API"

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("TODO App")

        self.title_label = QLabel("Title:")
        self.title_input = QLineEdit()
        self.title_input.textChanged.connect(self.check)

        self.description_label = QLabel("Description:")
        self.description_input = QLineEdit()
        self.description_input.textChanged.connect(self.check)

        self.due_date_label = QLabel("Due Date:")
        self.due_date_input = QDateEdit()
        self.due_date_input.setDate(datetime.date.today())

        self.add_button = QPushButton("Add TODO")
        self.add_button.clicked.connect(self.add_todo)
        self.add_button.setEnabled(False)

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.title_label)
        self.layout.addWidget(self.title_input)
        self.layout.addWidget(self.description_label)
        self.layout.addWidget(self.description_input)
        self.layout.addWidget(self.due_date_label)
        self.layout.addWidget(self.due_date_input)
        self.layout.addWidget(self.add_button)

        self.central_widget = QWidget()
        self.central_widget.setLayout(self.layout)
        self.setCentralWidget(self.central_widget)
    
    
    def check(self):
        if len(self.title_input.text().strip()) > 0 and len(self.description_input.text().strip()) > 0:
            self.add_button.setEnabled(True)
        else:
            self.add_button.setEnabled(False)

    def add_todo(self):
        title = self.title_input.text()
        description = self.description_input.text()
        due_date = self.due_date_input.date().toString("dd-MM-yyyy")

        payload = {
            "title": title,
            "description": description,
            "dueDate": due_date,
            "done": False
        }

        response = requests.post(f"{API_BASE_URL}/add", json=payload)
        if response.status_code == requests.codes.CREATED:
            print("TODO added successfully!")
            self.title_input.setText("")
            self.description_input.setText("")
            self.due_date_input.setDate(datetime.date.today())
        else:
            print("Failed to add TODO.")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
